[package]
name = "durak"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.11.0", features = ["dynamic_linking"] }
rand = "0.8.5"
strum = { version = "0.25.0", features = ["derive"] }
